name: trigger 
database:
  postgres:
    columns:
    - name: id
      type: text
      from:
        type: resource
        path: Metadata.ID
    - name: userid
      type: text
      from:
        type: tenant
        path: Metadata.ID
    - name: info
      type: json
      from:
        type: resource
        path: .
    indexes:
      - [userid]
    primeryKey: [id]
tenant: user
rootAggregate:
  resource: Trigger 