name: list
tenant: user
root:
  resource: List
  database:
    name: list
    postgres:
      columns:
      - name: id
        type: text
        fromResource:
          as: string
          path: Metadata.ID
      - name: userid
        type: text
        fromTenant:
          as: string
          path: Metadata.ID
      - name: info
        type: json
        fromResource:
          as: string
          path: .
      indexes:
        - [userid]
      primeryKey: [id]